### ISSUE TITLE
Add the version of the code generator in the agent header

### ISSUE THREAD

**Issue by PierrickVoulet** [googleapis/gapic-generator-php#298] opened 2021-05-26 19:44 UTC
**Describe the solution you'd like**

All API requests are sent with `gapic/` in their agent headers which is great (so we know that it was generated by GAPIC) but it would be even better if the GAPIC version was added `gapic/x.y.z`.

**Describe alternatives you've considered**

None.

**Additional context**

As far as I know, this is done by other languages such as Dotnet, Ruby, Python to name a few.

**Comment by noahdietz** [comment] 2022-02-08 17:30
@PierrickVoulet it looks like gax-php has some code related to this.

The `AgentHeader` helper class will look up the GAPIC _client_ version from a `VERSION` file that should exist above the `src` dir ([code](https://github.com/googleapis/gax-php/blob/main/src/AgentHeader.php#L117-L140)). It is used to construct the `gapic/` value.

Now this gives you the version of the GAPIC _client_, not the _generator_ version used to generate that client.

In Go, Typescript, and PHP (from what I can tell), `gapic/` is meant to represent the version of the _library_, not the generator that generated it. If the library version is what you want, simply add the `VERSION` file to your client repo and it should "just work".

**Comment by noahdietz** [comment] 2022-02-08 17:31
To be clear, I was slightly confused by the issue title indicating "version of the code generator", but I _think_ you mean _library_ version.

**Comment by noahdietz** [comment] 2022-02-08 17:43
I've confirmed offline that `gapic/` is the version of the _library_.

So using the solution I described (adding `VERSION` file above `src/`) this should "just work". I'm going to close this, but if you want to reopen it or ask more questions, please feel free.

**Closed by noahdietz** 2022-02-08 17:43 UTC
Labels: type: bug, priority: p2
